version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  fhir-load:
    image: abuh12/fhir-load
    depends_on:
      db:
        condition: service_healthy
    command: --host=db --port=5432 --user=postgres --password=postgrespassword
    volumes:
      - 'logs:/fhir-load/logs'
      - 'path/to/data/directory:/fhir-load/data'
volumes:
  pgdata:
  logs: