CREATE TABLE encounters (
  full_url VARCHAR(45) PRIMARY KEY,
  request_method VARCHAR(7),
  request_url VARCHAR(50),
  resource_type VARCHAR(50),
  resource_id VARCHAR(),
  resource_profile TEXT,
  resource_status TEXT,
  resource_class_system TEXT,
  resource_class_code TEXT,
  resource_type_coding JSONB,
  resource_type_text TEXT,
  resource_subject_reference TEXT,
  resource_subject_display TEXT,
  resource_participant_type_coding JSONB,
  resource_participant_type_text TEXT,
  resource_participant_period_start TIMESTAMP WITH TIME ZONE,
  resource_participant_period_end TIMESTAMP WITH TIME ZONE,
  resource_participant_individual_reference TEXT,
  resource_participant_individual_display TEXT,
  resource_period_start TIMESTAMP WITH TIME ZONE,
  resource_period_end TIMESTAMP WITH TIME ZONE,
  resource_location_location_reference TEXT,
  resource_location_location_display TEXT,
  resource_service_provider_reference TEXT,
  resource_service_provider_display TEXT,
  resource_reason_code_coding JSONB,
  resource_hospitalization_discharge_disposition_coding JSONB,
  resource_hospitalization_discharge_disposition_text TEXT
);