CREATE TABLE encounters (
  id VARCHAR(45) PRIMARY KEY,
  request_method VARCHAR(7),
  request_url VARCHAR(50),
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  class_code VARCHAR(10),
  type_coding JSONB,
  type TEXT,
  subject_reference VARCHAR(45),
  subject TEXT,
  participant_type_coding JSONB,
  participant_type TEXT,
  participant_period_start TIMESTAMP WITH TIME ZONE,
  participant_period_end TIMESTAMP WITH TIME ZONE,
  participant_individual_reference TEXT,
  participant_individual TEXT,
  period_start TIMESTAMP WITH TIME ZONE,
  period_end TIMESTAMP WITH TIME ZONE,
  location_reference TEXT,
  location TEXT,
  service_provider_reference TEXT,
  service_provider TEXT,
  reason_code_coding JSONB,
  hospitalization_discharge_disposition_coding JSONB,
  hospitalization_discharge_disposition TEXT
);